name: Test Scraping

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set waktu ke WIB
        run: sudo timedatectl set-timezone Asia/Jakarta
    
      - name: Checkout ke branch
        uses: actions/checkout@v2 # checkout the repository content

      - name: Setup python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12.2' # install the python version needed

      - name: Install library python
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Menjalankan script scrapping
        run: scrapy crawl manga-spider
